### ISSUE TITLE
Project license

### ISSUE THREAD

**Issue by gsantner** [daviddurham/back-up#1]
Hello I found that game by looking for some simple small games to quickly open on phone.

I couldn't find any license information in this repository or a file.
What is the license of this project, MIT?
Can you please add a license file? 

Thanks :)
@daviddurham

**Comment by gsantner** [comment]
?

**Comment by l2toplist** [comment]
Hi, a very good script, can I voice the license under which you distribute the code? And just like compiling the source, there is no package.json, build?

**Comment by gsantner** [comment]
Whatever open source license you prefer is fine, except propritary and "no license" :)

**Comment by daviddurham** [comment]
Sorry for the delay. License information added.

**Comment by gsantner** [comment]
heres a gif for readme if you want to add it.


[back-up-game-demo.webm.zip](https://github.com/daviddurham/back-up/files/4605683/back-up-game-demo.webm.zip)


![back-up-game-demo](https://user-images.githubusercontent.com/6735650/81500063-1f508180-92bf-11ea-80db-8e9139d73811.gif)
